### ISSUE TITLE
Opaque material appears black and glitched (background repeats over it when i move the camera) But transparent works. 

### ISSUE THREAD

**Issue by ZirconGames** [Delt06/urp-toon-shader#52]
I'm having a trouble where a opaque material appears completely black:
![image](https://user-images.githubusercontent.com/69327974/194731251-1f3c1ae7-38c8-4f84-83d6-2a7aba0421c6.png)

And it glitches when i move the camera: 
![image](https://user-images.githubusercontent.com/69327974/194731284-673c9f05-f856-470b-bdd4-21dd06f426f2.png)

Doing that weird thing where it copies the border/background all over it. 
The lite shader works, but i really needed the full one with a normal map. Also, when i set it to transparent it works: 
![image](https://user-images.githubusercontent.com/69327974/194731316-717f46bf-ed00-45a8-b72e-e08ebec4d2b1.png)

I get no errors in the console, i've tried closing and opening the project, reimporting everything, nothing works.

I have unity 2021.3.8f1 and URP 12.1.7. This is probably something in my end, but i would appreciate some help if you know what could be causing this. Thank you!

**Comment by Delt06** [comment]
In the repo, there is a demo scene called `Additional Lights`. It also features a rock with normal mapped material.
Could you please try running it with your setup?

**Comment by Delt06** [comment]
Tried to run it using 2021.3.8f1 and URP 12.1.7, works as expected.
