### ISSUE TITLE
WebGL 2.0 Support

### ISSUE THREAD

**Issue by digimbyte** [Delt06/urp-toon-shader#54]
Looking to upgrade our outline shader and have been unable to find one that works,
is there a potential caveat or setting required to make this work with WebGL 2.0?

EDITOR:
(our original, URP Toon A, URP Toon B)
![image](https://user-images.githubusercontent.com/6645396/230357596-ccefa0bd-55f4-4137-af93-6cb97856ffe6.png)

WebGL:
![image](https://user-images.githubusercontent.com/6645396/230357679-65da1347-fe7b-4fbd-b245-c0673a013930.png)

end goal is to get it to work in WebGL and then fix the scale/push of the mesh based on a Fresnel

**Comment by Delt06** [comment]
I remember running the outline in WebGL, it was working at the time. However, there were artifacts with the Clip Space option (#44).
I will check this with the newest version of the shader a bit later.

**Comment by Delt06** [comment]
I was able to successfully run the "Inverted Hull Outline" scene (it's in the repo)
![image](https://user-images.githubusercontent.com/32465621/230384063-fa7d92f8-1fd7-45d0-8ea3-99b75af0331d.png)

**Comment by digimbyte** [comment]
I'll continue to debug this, perhaps an option or setting was missing
