### ISSUE TITLE
Feature: Camera bias for Hull displacement

### ISSUE THREAD

**Issue by digimbyte** [Delt06/urp-toon-shader#55]
one main issue with Hull outlines is the gap it creates between the displaced verts and the underlaying mesh.
can we introduce some sort of dot product bias that multiplies the vert distance by the view direction?

in theory this would reduce any depth bleeding from neighbors

**Comment by Delt06** [comment]
Is this the gap you are talking about?
https://github.com/Delt06/urp-toon-shader/wiki/Outline#issue-1-outlines-of-objects-with-sharp-normals-get-disconnected

If so, it's caused by discontinuities in the object's normals. Please see the linked wiki page for a possible fix.

**Comment by digimbyte** [comment]
I am referring to the displacement gap of hulls, the issue is that its universal from the mesh normal rather than bias from the camera angle. Say if you have hair or an arm and its too close to another, by default, the displaced hull would project through the other face simple because its multiplying the distance by the input value.

adding a bias that multiplies the distance from -1 to 1 we can pinch the displacement, hiding the gap between neighbors
effectively making a billboard that is relational to the camera

**Comment by Delt06** [comment]
Please check the `view-bias` branch. I added `View Bias Threshold` and `View Bias Smoothness` parameters to the Inverted Hull Outline shader. 
Using them and the `Depth Offset Factor` should help eliminate most such artifacts.

**Comment by digimbyte** [comment]
![image](https://user-images.githubusercontent.com/6645396/230757393-1fda5cdc-9bd9-49fb-ae20-47b495aca8b1.png)
(sphere with extreme hull shader depth)
the depth offset helps the most, but would require displacement scaling.

in shaders, if you use a Fresnel as a "filter" with multiplication, it would help even more as there is no sense in displacing the vertex on the backface if its not seen

**Comment by digimbyte** [comment]
seems like the updates targets the edge verts first rather than the behind
![image](https://user-images.githubusercontent.com/6645396/230758212-52240346-73ad-45d1-8a20-93339802a79a.png)
