### ISSUE TITLE
Outline Wiki should include Outline Toolkit as requirement

### ISSUE THREAD

**Issue by Velite12** [Delt06/urp-toon-shader#56]
I was having issues as to why the Inverted Hull Outline wasn't working until I went to the Forest Demo Page and found a link to https://github.com/Arvtesh/UnityFx.Outline, the Outline Toolkit which is a requirement for the Inverted Hull Outline to work, it should be listed on the Outline guide as well.

Just add a link to https://github.com/Arvtesh/UnityFx.Outline in the Outline Wiki.

**Comment by Delt06** [comment]
Inverted Hull Outlines are not using the Outline Toolkit and can work out of the box. The Forest demo is, indeed, using the external package, but bundled outlines should work by themselves. 

What exact problems were you having when trying to configure Inverted Hull Outline?

**Comment by Velite12** [comment]
Out of the box, the Inverted Hull Outlines were not working in 2022, I even opened a fresh new project in 2021.3 and they would not work (as in, the Inverted Hull Outline was not showing at all) out of the box as instructed. Once I got the Outline Toolkit package, core and URP, in the project, they started to work. The Toon Shader is working fine with no issues. I can cofigure the Inverted Hull Material now and the effects show in game.

The only problem I am encountering is that the Outlines are not visible if Depth is turned on but Depth Write is turned off in the Render Feature, as instructed in fixing the Outlines going through objects. I have to turn both on or turn Depth off.

**Comment by Delt06** [comment]
> Out of the box, the Inverted Hull Outlines were not working in 2022, I even opened a fresh new project in 2021.3 and they would not work (as in, the Inverted Hull Outline was not showing at all) out of the box as instructed. Once I got the Outline Toolkit package, core and URP, in the project, they started to work. The Toon Shader is working fine with no issues. I can cofigure the Inverted Hull Material now and the effects show in game.

Can you please provide a screenshot with the settings you used in the new project before importing the Outline Toolkit package? Just to make sure, I created a new project and added URP Toon Shader package, set up everything up, and it seems to work

![image](https://github.com/Delt06/urp-toon-shader/assets/32465621/6d0966c0-b78e-4f71-a309-96073ffbcfd6)


> The only problem I am encountering is that the Outlines are not visible if Depth is turned on but Depth Write is turned off in the Render Feature, as instructed in fixing the Outlines going through objects. I have to turn both on or turn Depth off.

For that one, is your background just a skybox? In this case, it may happen. A fix may be to change the event to "AfterRenderingSkybox"

**Comment by Velite12** [comment]
This is going to sound funny but now I can't replicate the issue. I was able to get it to work out of the box in 2021.3 now. And for 2022 I removed the Outline Toolkit and I still have the Outlines.

Also changing the event did the trick. Thanks, I'll close this issue.
