### ISSUE TITLE
Having trouble getting this to work on Android

### ISSUE THREAD

**Issue by Velite12** [Delt06/urp-toon-shader#57]
Hi, I love the way the toon shader looks on PC, but the same settings I'm using in the editor and PC do not come out the same way on Android mobile devices.

Here's a comparison, Android:
![Screenshot_20230703_215235_Sphere Guider](https://github.com/Delt06/urp-toon-shader/assets/45871932/f77101f7-c42e-4b7d-9b6e-19f0d817214e)

vs Editor:
![Screenshot 2023-07-03 215212](https://github.com/Delt06/urp-toon-shader/assets/45871932/60cd76fc-1345-44b5-ba36-5dd1c65bb07b)

I know that it's definitely caused by the URP renderer because turning renderer features off disables them on Android, but I've tried changing settings and nothing actually seems to work. So if there's any approach you can think of, don't hesitate to let me know.

**Comment by Delt06** [comment]
Hi!
Could you send me a screenshot of the outline material and render feature setings?
Also, what are the device and the graphical API (preferrably, with version) you use?

**Comment by Velite12** [comment]
Hello, I found that I actually solved the issue on my own. It turns out all I needed to do was to switch from OpenGLES to Vulcan in the player settings.
