### ISSUE TITLE
How to get transparency using the Inverted Hull Outline for a specific object

### ISSUE THREAD

**Issue by Velite12** [Delt06/urp-toon-shader#59]
Hello, so I have this situation, where I want to make objects that are between the player and the camera transparent. I managed to achieve this for objects without outlines:

![transparent platform](https://github.com/Delt06/urp-toon-shader/assets/45871932/5a57e67f-fb6f-4c84-916e-0ff483ff4726)

However, objects with the inverted hull outline look like this:

![nontransparent outline platform](https://github.com/Delt06/urp-toon-shader/assets/45871932/32c99531-4343-460b-8d7d-7c0023d0f15d)

Even if I manage to completely fade out the object, the outline remains opaque:

![object hidden but outline isn't](https://github.com/Delt06/urp-toon-shader/assets/45871932/714b2cf2-ab47-45d6-b354-d8004ff342df)

Is there a way to achieve transparency with a specific object's outline?

**Comment by Delt06** [comment]
The outline approach itself requires both objects and outlines to be opaque since we are actively relying on death read/writes.

I have this alternatives in mind:
- to ensure player is always visible, you can render it's silhouette when it's failing depth test: https://www.youtube.com/watch?v=GAh225QNpm0
- at the same time when you make objects transparent, disable their outlines by changing the game object's layer

**Comment by Velite12** [comment]
> The outline approach itself requires both objects and outlines to be opaque since we are actively relying on death read/writes.
> 
> I have this alternatives in mind:
> 
>     * to ensure player is always visible, you can render it's silhouette when it's failing depth test: https://www.youtube.com/watch?v=GAh225QNpm0
> 
>     * at the same time when you make objects transparent, disable their outlines by changing the game object's layer

Yes, I was actually considering the second option. I would have liked the outline to be faded but it is what it is. I have a dedicated layer for no outlines that I can swap it to. Thanks!

**Comment by Delt06** [comment]
You can also make a copy of the shader and make outlines thickness fade to 0 based on the distance to the camera. The shader itself is quite simple, and I think this effect will make the transition much better.
